### ISSUE TITLE
Velero can be included in User managed plugin / extensions . 

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#139]
**Describe the bug**
In TKO solution, Velero can be included in User managed plugin / extensions .

**Comment by manishjha86** [comment]
For the 1.5 docs, we have created a dedicated RA and Deploy Guide for data protection in TKO. The deploy guide demonstrates enabling data protection through TMC which eventually installs Velero in the workload cluster selected for data protection.

Installing Velero standalone will be only part of the airgap docs as there is no internet available there. For internet-based environments, its recommended to use TMC

**Comment by manishjha86** [comment]
Data protection RA: https://github.com/manishjha86/tanzu-validated-solutions/blob/data-protection-ra/src/reference-designs/tko-data-protection.md

Data protection Deploy Guide: https://github.com/manishjha86/tanzu-validated-solutions/blob/data-protection-dg/src/deployment-guides/tkg-data-protection.md

Since these files resides in separate branch in my forked repo, you might see a 404 if trying to access the doc from any other branch.
