### ISSUE TITLE
[TKO vSphere with Tanzu RA] Observability

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu-labs/tanzu-validated-solutions#54]
1. Why talk about prometheus and grafana.  TKO includes TO.  Assume full TKO purchase in the RA.
2. Should be clear in terms of deploy TO via TMC
3. Should talk about the Avi TO Integration and setting that up

**Comment by manishjha86** [comment]
Here are the responses regarding the feedback:

1: Prometheus and Grafana are talked about because they are part of user-managed packages. RA does recommend the use of TO for monitoring, but it doesn't enforce the same. If customers have a specific use case of using Prometheus and Grafana, they should be knowing about the packages and a way to deploy them via TMC.

2: Deploy TO via TMC is part of the deploy guide. We can add a one-liner in RA that TO can be enabled directly from TMC. 

@doddatpivotal can you please provide more context regarding point#3 "Avi TO Integration". What exactly we are talking about here.

**Comment by manishjha86** [comment]
@doddatpivotal we are still waiting for clarification on point#3

**Comment by nithink-vmw** [comment]
@doddatpivotal  , We have provided high-level details about extensions and are in the process of creating detailed docs specific to extensions. 
Due to the fact that we are creating a single RA to serve Internet-/Proxy-/Airgap-based customers, we have included both options for monitoring.
