### ISSUE TITLE
Add references to shared services cluster in TKO on Azure RA and deployment docs

### ISSUE THREAD

**Issue by srinivasme21** [vmware-tanzu-labs/tanzu-validated-solutions#78]
tko-on-azure RA: Add reference to shared services cluster and examples of which services are installed on a shared services cluster to the RA.
Add deployment instructions to the deployment doc.

**Comment by brharr** [comment]
The decision was made during the creation of the first version of the RA that Harbor was not a required component, especially within a CSP native implementation like Azure and AWS due to the fact that they have their own registries. In addition, Harbor is not a required piece for TKO just that a registry exist. 

A reference to the optional install of Harbor was put in the RA and that it would need to go into a Workload cluster. Due to its lack of requirement in the RA, there is no need to require it in the Deployment Guide either. There is a reference to the documentation for how to install it should a customer want to and there is clearly a reference to a "Shared Cluster" within that documentation.
